# ---------------- Train ---------------- #

# config: "default.yaml" # path to config
exp_name: "test" # the name of this experiment
seed: 1 # seed of the experiment
torch_deterministic: true # if toggled, `torch.backends.cudnn.deterministic=False`
cuda: true # if toggled, cuda will be enabled by default
track: false # if toggled, this experiment will be tracked with Weights and Biases
wandb_project_name: "cleanRL" # the wandb's project name
wandb_entity: null # the entity (team) of wandb's project
capture_video: false # whether to capture videos of the agent performances (check out `videos` folder)
checkpoint_frequency: 50 # save agent every n update epochs

# Algorithm specific arguments
env_id: "CartPole-v1" # the id of the environment
total_timesteps: 50000 # total timesteps of the experiments
learning_rate: 2.5e-4 # the learning rate of the optimizer
num_envs: 4 # the number of parallel game environments
num_steps: 128 # the number of steps to run in each environment per policy rollout
anneal_lr: true # Toggle learning rate annealing for policy and value networks
gamma: 0.99 # the discount factor gamma
gae_lambda: 0.95 # the lambda for the general advantage estimation
num_minibatches: 4 # the number of mini-batches
update_epochs: 4 # the K epochs to update the policy
norm_adv: true # Toggles advantages normalization
clip_coef: 0.2 # the surrogate clipping coefficient
clip_vloss: true # Toggles whether or not to use a clipped loss for the value function, as per the paper.
ent_coef: 0.01 # coefficient of the entropy
vf_coef: 0.5 # coefficient of the value function
max_grad_norm: 0.5 # the maximum norm for the gradient clipping
target_kl: null # the target KL divergence threshold

# ---------------- Tune ---------------- #
script: "train.py" # training script to run
metric: "charts/episodic_return" # metric to use for tuning
metric_last_n_average_window: 50 # window over witch the metric gets averaged
direction: "maximize" # direction in witch to optimize
aggregation_type: "average" # aggregation type for multiple environments
target_scores: # lower and upper bound for reward per environment
  CartPole-v1: 
    - 0
    - 500

# hyperparameter options
learning_rate_o: # range for learning rate tuning
  min: 0.0003 # lower bound
  max: 0.003 # upper bound
  log: true # use logarithmic distribution
num_minibatches_o: # options for number of minibatches
  - 1
  - 2
  - 4
update_epochs_o: # options for number of epochs per update
  - 1
  - 2
  - 4
  - 8
num_steps_o: # options for number of steps to run in each environment per policy rollout
  - 5 
  - 16
  - 32
  - 64
  - 128
vf_coef_o: # range for coefficient of the value function
  min: 0 # lower bound
  max: 5 # upper bound
  log: false # use logarithmic distribution
max_grad_norm_o: # range for the maximum norm for the gradient clipping
  min: 0 # lower bound
  max: 5 # upper bound
  log: false # use logarithmic distribution
total_timesteps_per_trial: 100000

# trial options
storage: "sqlite:///tune.db" # storage location of tuning database
num_trials: 100 # number of trials to optimize over
num_seeds: 3 # number of seeds/experiments per trial